GPP=g++
FLAGS=-g

CPPFILES=main.cpp base.cpp room.cpp trigger.cpp turnon.cpp item.cpp creature.cpp container.cpp border.cpp condition.cpp attack.cpp

all: $(CPPFILES)
	$(GPP) $(FLAGS) $(CPPFILES)


clean:
	rm -f *.o *.out *.output